platform:
  - x64
  - x86

environment:
  matrix:
    - RUST_VERSION: stable
      VENDOR: gnu
    - RUST_VERSION: stable
      VENDOR: msvc
    - RUST_VERSION: 1.16.0
      VENDOR: gnu
    - RUST_VERSION: 1.16.0
      VENDOR: msvc
    - RUST_VERSION: beta
      VENDOR: gnu
    - RUST_VERSION: beta
      VENDOR: msvc

install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
          $arch = "i686"
      }
      else {
          $arch = "x86_64"
      }
      if ($env:RUST_VERSION -eq "stable") {
        Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable" -FileName "channel-rust-stable"
        $installer = Get-Content "channel-rust-stable" | Select-String -Pattern "$arch-pc-windows-${env:VENDOR}.exe"
      }
      else {
        $installer = "rust-${env:RUST_VERSION}-$arch-pc-windows-${env:VENDOR}.exe"
      }
      Start-FileDownload "https://static.rust-lang.org/dist/$installer" -FileName rust-install.exe
  - rust-install.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - "cargo build --verbose --package serial-core"
  - "cargo test --verbose --package serial-core"
  - "cargo build --verbose --package serial-windows"
  - "cargo test --verbose --package serial-windows"
  - "cargo build --verbose --package serial"
  - "cargo test --verbose --package serial"
